# Generated by Django 4.2.23 on 2025-07-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("pub_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "предмет",
                "verbose_name_plural": "предмет",
                "ordering": ("-pub_date",),
            },
        ),
    ]
