# Generated by Django 4.2.23 on 2025-08-17 08:19

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vehicle", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Удалён"),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название атрибута"),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Единицы измерения"
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("str", "String"),
                            ("int", "Integer"),
                            ("float", "Float"),
                        ],
                        max_length=50,
                        verbose_name="Тип данных",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SparePart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Удалён"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INSTALLED", "Установлено"),
                            ("IN_STOCK", "На складе"),
                            ("REPAIR", "В ремонте"),
                            ("AWAITING_REPAIR", "Ожидает ремонт"),
                        ],
                        default="INSTALLED",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SparePartType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Удалён"),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название типа"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SparePartLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата изменения"
                    ),
                ),
                ("message", models.TextField(verbose_name="Комментарий об изменении")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Удалён"),
                ),
                (
                    "spare_part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="spare_parts.sparepart",
                        verbose_name="Запчасть",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SparePartImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Удалён"),
                ),
                (
                    "file",
                    sorl.thumbnail.fields.ImageField(
                        upload_to="spare_part_images/", verbose_name="Фото"
                    ),
                ),
                (
                    "spare_part_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="spare_parts.spareparttype",
                        verbose_name="Тип запчасти",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="sparepart",
            name="spare_part_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="spare_parts.spareparttype",
                verbose_name="Тип запчасти",
            ),
        ),
        migrations.AddField(
            model_name="sparepart",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spare_parts",
                to="vehicle.vehicle",
                verbose_name="Техника",
            ),
        ),
        migrations.CreateModel(
            name="AttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Удалён"),
                ),
                ("value", models.CharField(max_length=255, verbose_name="Значение")),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spare_parts.attribute",
                        verbose_name="Атрибут",
                    ),
                ),
                (
                    "spare_part_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spare_parts.spareparttype",
                        verbose_name="Тип запчасти",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
